### ISSUE TITLE
Attempting to add this as a datasource in grafana helmchart 

### ISSUE THREAD

**Issue by cgibbs35** [wildmountainfarms/wild-graphql-datasource#11]
i'm attempting to add this as a datasource in the grafana helm chart under 

```yaml
datasources:
  datasources.yaml:
    - name: test
       type: Wild GraphQL Data Source
       url: <my-url>
       jsondata:
          headers:
            - key: value
```

the problem im running into is i do not know what yaml format looks like for this plugin, i need to add some custom headers to where i am querying and the default grafana datasource layout isnt exactly clear on how the key/values should be configured, i've tried a bit of trial and error but not luck so far. im wondering if some of these values can be added to the datasources.yaml in this repo.

**Comment by retrodaredevil** [comment]
Can you give this documentation a try? Honestly I'm not sure if it works, but in theory it should (I'll also try to test it on my own at some point) https://grafana.com/docs/grafana/latest/administration/provisioning/#custom-http-headers-for-data-sources

I wasn't the one that made the PR for HTTP header support (@hgiasac did a great job). My understanding is that for most Grafana datasources, adding HTTP headers is done in pretty much the same way for each datasource. If that's the case, you should be able to provision HTTP headers in the same way for most datasources.

**Comment by cgibbs35** [comment]
I think i saw this section right after i posted let me test to make sure that works for this plugin.

**Comment by cgibbs35** [comment]
yep that format worked just did something like this incase anyone wants to use it or add it to plugin docs. 

```yaml
      - name: <name>
        type: retrodaredevil-wildgraphql-datasource
        url: <url>
        jsonData:
          httpHeaderName1: 'header'
        secureJsonData:
          httpHeaderValue1: 'value'
```
